name: lifestory
description: A platform for creating and sharing personal stories
version: 1.0.0
author: Joshua Abrams
environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  assets:
    - assets/logo.png
